# Generated by Django 4.1 on 2022-09-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IOCS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "ip",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "md5",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "sha1",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "sha256",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        default="No information", max_length=255, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.URLField(null=True)),
                ("details", models.TextField(max_length=255, null=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("time", models.DateTimeField(auto_now=True)),
                ("is_approve", models.BooleanField(default=False)),
                (
                    "iocs",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iocs",
                        to="reports.iocs",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
