# Generated by Django 4.1 on 2022-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_iocs_cve_iocs_domain_iocs_email_iocs_ip_iocs_md5_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iocs",
            name="cve",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="domain",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="email",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="ip",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="md5",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="sha1",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="sha256",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iocs",
            name="url",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
