# Generated by Django 4.0.4 on 2022-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_iocs_cve_alter_iocs_domain_alter_iocs_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
