# Generated by Django 4.1 on 2022-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_iocs_cve_alter_iocs_domain_alter_iocs_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
